name = "no-redeclare-initialize-access-control"
description = "Do NOT redeclare _initializeAccessControl — it is provided by MixinAuthorization"
query = """
(source_file
  (obj_dec "actor"
    (obj_body
      (dec_field
        (func_dec
          (_) @error
          (#eq? @error "_initializeAccessControl"))))))
(source_file
  (class_dec "actor"
    (obj_body
      (dec_field
        (func_dec
          (_) @error
          (#eq? @error "_initializeAccessControl"))))))
"""
