/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AgmUserRole = IDL.Variant({
  'Viewer' : IDL.Null,
  'RegistrationOfficer' : IDL.Null,
  'ReportsViewer' : IDL.Null,
  'BoardViewer' : IDL.Null,
  'Admin' : IDL.Null,
  'SuperAdmin' : IDL.Null,
});
export const AgmLoginResponse = IDL.Record({
  'token' : IDL.Text,
  'username' : IDL.Text,
  'role' : AgmUserRole,
  'mustChangePassword' : IDL.Bool,
});
export const AgmSession = IDL.Record({
  'token' : IDL.Text,
  'expiresAt' : IDL.Int,
  'username' : IDL.Text,
  'role' : AgmUserRole,
});
export const AgmShareholderStatus = IDL.Variant({
  'CheckedIn' : IDL.Null,
  'NotRegistered' : IDL.Null,
  'RegisteredInPerson' : IDL.Null,
  'RegisteredProxy' : IDL.Null,
});
export const AgmShareholderInput = IDL.Record({
  'email' : IDL.Opt(IDL.Text),
  'fullName' : IDL.Text,
  'idNumber' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
  'shareholderNumber' : IDL.Text,
  'shareholding' : IDL.Nat,
  'tags' : IDL.Vec(IDL.Text),
});
export const AgmShareholder = IDL.Record({
  'email' : IDL.Opt(IDL.Text),
  'fullName' : IDL.Text,
  'id' : IDL.Text,
  'idNumber' : IDL.Text,
  'importedAt' : IDL.Int,
  'importedBy' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
  'shareholderNumber' : IDL.Text,
  'shareholding' : IDL.Nat,
  'status' : AgmShareholderStatus,
  'tags' : IDL.Vec(IDL.Text),
});
export const AgmSearchResult = IDL.Record({
  'items' : IDL.Vec(AgmShareholder),
  'page' : IDL.Nat,
  'total' : IDL.Nat,
});
export const AgmRegistrationType = IDL.Variant({
  'InPerson' : IDL.Null,
  'Proxy' : IDL.Null,
});
export const AgmProxyData = IDL.Record({
  'proxyContact' : IDL.Text,
  'proxyName' : IDL.Text,
  'proxyProofKey' : IDL.Opt(IDL.Text),
});
export const AgmRegistration = IDL.Record({
  'id' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'proxyContact' : IDL.Opt(IDL.Text),
  'proxyFraudFlags' : IDL.Vec(IDL.Text),
  'proxyName' : IDL.Opt(IDL.Text),
  'proxyProofKey' : IDL.Opt(IDL.Text),
  'proxyProofValidated' : IDL.Bool,
  'registeredAt' : IDL.Int,
  'registeredBy' : IDL.Text,
  'registrationType' : AgmRegistrationType,
  'shareholderId' : IDL.Text,
  'updatedAt' : IDL.Int,
  'updatedBy' : IDL.Opt(IDL.Text),
  'verificationCode' : IDL.Text,
});
export const AgmRegistrationUpdate = IDL.Record({
  'notes' : IDL.Opt(IDL.Text),
  'proxyData' : IDL.Opt(AgmProxyData),
  'registrationType' : IDL.Opt(AgmRegistrationType),
  'verificationCode' : IDL.Opt(IDL.Text),
});
export const AgmCheckInMethod = IDL.Variant({
  'Manual' : IDL.Null,
  'ManualQuick' : IDL.Null,
  'QRScan' : IDL.Null,
});
export const AgmCheckIn = IDL.Record({
  'checkedInAt' : IDL.Int,
  'checkedInBy' : IDL.Text,
  'id' : IDL.Text,
  'method' : AgmCheckInMethod,
  'registrationId' : IDL.Text,
  'shareholderId' : IDL.Text,
});
export const AgmBulkCreateResult = IDL.Record({
  'created' : IDL.Nat,
  'duplicates' : IDL.Nat,
  'errors' : IDL.Vec(IDL.Text),
});
export const AgmImportStatus = IDL.Variant({
  'Complete' : IDL.Null,
  'Failed' : IDL.Null,
  'Pending' : IDL.Null,
  'Processing' : IDL.Null,
});
export const AgmImportBatch = IDL.Record({
  'duplicatesSkipped' : IDL.Nat,
  'filename' : IDL.Text,
  'id' : IDL.Text,
  'importedRows' : IDL.Nat,
  'status' : AgmImportStatus,
  'totalRows' : IDL.Nat,
  'uploadedAt' : IDL.Int,
  'uploadedBy' : IDL.Text,
});
export const AgmDashboardMetrics = IDL.Record({
  'attendanceRate' : IDL.Float64,
  'checkedIn' : IDL.Nat,
  'lastUpdated' : IDL.Int,
  'notRegistered' : IDL.Nat,
  'quorumStatus' : IDL.Bool,
  'registered' : IDL.Nat,
  'registeredInPerson' : IDL.Nat,
  'registeredProxy' : IDL.Nat,
  'totalShareholders' : IDL.Nat,
});
export const AgmSettings = IDL.Record({
  'agmDate' : IDL.Text,
  'agmName' : IDL.Text,
  'quorumThreshold' : IDL.Nat,
  'sessionTimeoutMinutes' : IDL.Nat,
  'venue' : IDL.Text,
});
export const AgmAuditEntry = IDL.Record({
  'action' : IDL.Text,
  'details' : IDL.Text,
  'entityId' : IDL.Text,
  'entityType' : IDL.Text,
  'id' : IDL.Text,
  'ipAddress' : IDL.Opt(IDL.Text),
  'performedAt' : IDL.Int,
  'performedBy' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AnnouncementCategory = IDL.Variant({
  'HR' : IDL.Null,
  'IT' : IDL.Null,
  'General' : IDL.Null,
});
export const CreateAnnouncementInput = IDL.Record({
  'title' : IDL.Text,
  'imageFile' : IDL.Opt(ExternalBlob),
  'body' : IDL.Text,
  'authorName' : IDL.Text,
  'allowDownload' : IDL.Bool,
  'category' : AnnouncementCategory,
});
export const Timestamp = IDL.Int;
export const AnnouncementPublic = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isDeleted' : IDL.Bool,
  'imageFile' : IDL.Opt(ExternalBlob),
  'authorId' : IDL.Text,
  'body' : IDL.Text,
  'authorName' : IDL.Text,
  'allowDownload' : IDL.Bool,
  'datePosted' : Timestamp,
  'category' : AnnouncementCategory,
});
export const FormCategory = IDL.Variant({
  'HR' : IDL.Null,
  'IT' : IDL.Null,
  'General' : IDL.Null,
  'Operations' : IDL.Null,
  'Finance' : IDL.Null,
});
export const CreateFormInput = IDL.Record({
  'title' : IDL.Text,
  'filename' : IDL.Text,
  'category' : FormCategory,
});
export const Form = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'filename' : IDL.Text,
  'category' : FormCategory,
  'uploadDate' : Timestamp,
});
export const UserId = IDL.Principal;
export const CreateNotificationInput = IDL.Record({
  'title' : IDL.Text,
  'userId' : UserId,
  'link' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
});
export const NotificationPublic = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'userId' : IDL.Text,
  'link' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const CreatePollInput = IDL.Record({
  'question' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
  'announcementId' : IDL.Nat,
});
export const Poll = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'announcementId' : IDL.Nat,
});
export const Branch = IDL.Variant({
  'Bawjiase' : IDL.Null,
  'KasoaMain' : IDL.Null,
  'Ofaakor' : IDL.Null,
  'HeadOffice' : IDL.Null,
  'Adeiso' : IDL.Null,
  'KasoaNewMarket' : IDL.Null,
});
export const Role = IDL.Variant({
  'HRAdmin' : IDL.Null,
  'GeneralStaff' : IDL.Null,
  'SuperAdmin' : IDL.Null,
});
export const Department = IDL.Variant({
  'HR' : IDL.Null,
  'IT' : IDL.Null,
  'Susu' : IDL.Null,
  'Compliance' : IDL.Null,
  'Bawjiase' : IDL.Null,
  'Recovery' : IDL.Null,
  'EBanking' : IDL.Null,
  'KasoaMain' : IDL.Null,
  'Admin' : IDL.Null,
  'Credit' : IDL.Null,
  'Ofaakor' : IDL.Null,
  'Audit' : IDL.Null,
  'HeadOffice' : IDL.Null,
  'Adeiso' : IDL.Null,
  'KasoaNewMarket' : IDL.Null,
  'Microfinance' : IDL.Null,
  'BankingOperations' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'branch' : Branch,
  'imageFile' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'role' : Role,
  'isArchived' : IDL.Bool,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'fullname' : IDL.Text,
  'isVerified' : IDL.Bool,
  'phone' : IDL.Text,
  'department' : Department,
  'position' : IDL.Text,
  'registrationTime' : IDL.Int,
  'lastSeen' : IDL.Int,
});
export const PollOptionResult = IDL.Record({
  'votedByMe' : IDL.Bool,
  'optionId' : IDL.Nat,
  'voteCount' : IDL.Nat,
  'optionText' : IDL.Text,
});
export const PollResult = IDL.Record({
  'question' : IDL.Text,
  'options' : IDL.Vec(PollOptionResult),
  'pollId' : IDL.Nat,
});
export const AnnouncementWithPoll = IDL.Record({
  'poll' : IDL.Opt(PollResult),
  'announcement' : AnnouncementPublic,
});
export const AuditLog = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'actorName' : IDL.Text,
  'target' : IDL.Text,
  'timestamp' : IDL.Int,
  'ipAddress' : IDL.Text,
});
export const StaffStats = IDL.Record({
  'branchesWithStaff' : IDL.Nat,
  'activeCount' : IDL.Nat,
  'archivedCount' : IDL.Nat,
});
export const RegisterRequest = IDL.Record({
  'branch' : Branch,
  'accessCode' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'fullname' : IDL.Text,
  'passwordHash' : IDL.Text,
  'phone' : IDL.Text,
  'department' : Department,
  'position' : IDL.Text,
});
export const UpdateAnnouncementInput = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'imageFile' : IDL.Opt(ExternalBlob),
  'body' : IDL.Text,
  'allowDownload' : IDL.Bool,
  'category' : AnnouncementCategory,
});
export const UpdateFormInput = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'filename' : IDL.Text,
  'category' : FormCategory,
});
export const UpdateProfileRequest = IDL.Record({
  'imageFile' : IDL.Opt(ExternalBlob),
  'fullname' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const UpdateStaffRequest = IDL.Record({
  'branch' : IDL.Opt(Branch),
  'role' : IDL.Opt(Role),
  'department' : IDL.Opt(Department),
  'position' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'archiveStaff' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmPasswordReset' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createAnnouncement' : IDL.Func(
      [CreateAnnouncementInput],
      [AnnouncementPublic],
      [],
    ),
  'createForm' : IDL.Func([CreateFormInput], [Form], []),
  'createNotification' : IDL.Func(
      [CreateNotificationInput],
      [NotificationPublic],
      [],
    ),
  'createPoll' : IDL.Func([CreatePollInput], [Poll], []),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteAuditLog' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteAuditLogs' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteForm' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteStaff' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getActiveStaff' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(AnnouncementWithPoll)], ['query']),
  'getArchivedStaff' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getForms' : IDL.Func([], [IDL.Vec(Form)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(NotificationPublic)], ['query']),
  'getPollResult' : IDL.Func([IDL.Nat], [IDL.Opt(PollResult)], ['query']),
  'getStaffMember' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'getStaffStats' : IDL.Func([], [StaffStats], ['query']),
  'getTrashedAnnouncements' : IDL.Func(
      [],
      [IDL.Vec(AnnouncementPublic)],
      ['query'],
    ),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'hideAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logAction' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'logAnnouncementDownload' : IDL.Func([IDL.Nat], [], []),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
      [],
    ),
  'logout' : IDL.Func([], [], []),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'permanentDeleteAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'register' : IDL.Func(
      [RegisterRequest],
      [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
      [],
    ),
  'requestPasswordReset' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'resendVerificationCode' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'restoreAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'restoreStaff' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateAnnouncement' : IDL.Func(
      [UpdateAnnouncementInput],
      [IDL.Opt(AnnouncementPublic)],
      [],
    ),
  'updateForm' : IDL.Func([UpdateFormInput], [IDL.Opt(Form)], []),
  'updateLastSeen' : IDL.Func([], [], []),
  'updateMyProfile' : IDL.Func(
      [UpdateProfileRequest],
      [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
      [],
    ),
  'updateStaff' : IDL.Func(
      [IDL.Principal, UpdateStaffRequest],
      [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
      [],
    ),
  'verifyEmail' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'vote' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AnnouncementCategory = IDL.Variant({
    'HR' : IDL.Null,
    'IT' : IDL.Null,
    'General' : IDL.Null,
  });
  const CreateAnnouncementInput = IDL.Record({
    'title' : IDL.Text,
    'imageFile' : IDL.Opt(ExternalBlob),
    'body' : IDL.Text,
    'authorName' : IDL.Text,
    'allowDownload' : IDL.Bool,
    'category' : AnnouncementCategory,
  });
  const Timestamp = IDL.Int;
  const AnnouncementPublic = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isDeleted' : IDL.Bool,
    'imageFile' : IDL.Opt(ExternalBlob),
    'authorId' : IDL.Text,
    'body' : IDL.Text,
    'authorName' : IDL.Text,
    'allowDownload' : IDL.Bool,
    'datePosted' : Timestamp,
    'category' : AnnouncementCategory,
  });
  const FormCategory = IDL.Variant({
    'HR' : IDL.Null,
    'IT' : IDL.Null,
    'General' : IDL.Null,
    'Operations' : IDL.Null,
    'Finance' : IDL.Null,
  });
  const CreateFormInput = IDL.Record({
    'title' : IDL.Text,
    'filename' : IDL.Text,
    'category' : FormCategory,
  });
  const Form = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'filename' : IDL.Text,
    'category' : FormCategory,
    'uploadDate' : Timestamp,
  });
  const UserId = IDL.Principal;
  const CreateNotificationInput = IDL.Record({
    'title' : IDL.Text,
    'userId' : UserId,
    'link' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
  });
  const NotificationPublic = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'userId' : IDL.Text,
    'link' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const CreatePollInput = IDL.Record({
    'question' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
    'announcementId' : IDL.Nat,
  });
  const Poll = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'announcementId' : IDL.Nat,
  });
  const Branch = IDL.Variant({
    'Bawjiase' : IDL.Null,
    'KasoaMain' : IDL.Null,
    'Ofaakor' : IDL.Null,
    'HeadOffice' : IDL.Null,
    'Adeiso' : IDL.Null,
    'KasoaNewMarket' : IDL.Null,
  });
  const Role = IDL.Variant({
    'HRAdmin' : IDL.Null,
    'GeneralStaff' : IDL.Null,
    'SuperAdmin' : IDL.Null,
  });
  const Department = IDL.Variant({
    'HR' : IDL.Null,
    'IT' : IDL.Null,
    'Susu' : IDL.Null,
    'Compliance' : IDL.Null,
    'Bawjiase' : IDL.Null,
    'Recovery' : IDL.Null,
    'EBanking' : IDL.Null,
    'KasoaMain' : IDL.Null,
    'Admin' : IDL.Null,
    'Credit' : IDL.Null,
    'Ofaakor' : IDL.Null,
    'Audit' : IDL.Null,
    'HeadOffice' : IDL.Null,
    'Adeiso' : IDL.Null,
    'KasoaNewMarket' : IDL.Null,
    'Microfinance' : IDL.Null,
    'BankingOperations' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'branch' : Branch,
    'imageFile' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'role' : Role,
    'isArchived' : IDL.Bool,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'fullname' : IDL.Text,
    'isVerified' : IDL.Bool,
    'phone' : IDL.Text,
    'department' : Department,
    'position' : IDL.Text,
    'registrationTime' : IDL.Int,
    'lastSeen' : IDL.Int,
  });
  const PollOptionResult = IDL.Record({
    'votedByMe' : IDL.Bool,
    'optionId' : IDL.Nat,
    'voteCount' : IDL.Nat,
    'optionText' : IDL.Text,
  });
  const PollResult = IDL.Record({
    'question' : IDL.Text,
    'options' : IDL.Vec(PollOptionResult),
    'pollId' : IDL.Nat,
  });
  const AnnouncementWithPoll = IDL.Record({
    'poll' : IDL.Opt(PollResult),
    'announcement' : AnnouncementPublic,
  });
  const AuditLog = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'actorName' : IDL.Text,
    'target' : IDL.Text,
    'timestamp' : IDL.Int,
    'ipAddress' : IDL.Text,
  });
  const StaffStats = IDL.Record({
    'branchesWithStaff' : IDL.Nat,
    'activeCount' : IDL.Nat,
    'archivedCount' : IDL.Nat,
  });
  const RegisterRequest = IDL.Record({
    'branch' : Branch,
    'accessCode' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'fullname' : IDL.Text,
    'passwordHash' : IDL.Text,
    'phone' : IDL.Text,
    'department' : Department,
    'position' : IDL.Text,
  });
  const UpdateAnnouncementInput = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'imageFile' : IDL.Opt(ExternalBlob),
    'body' : IDL.Text,
    'allowDownload' : IDL.Bool,
    'category' : AnnouncementCategory,
  });
  const UpdateFormInput = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'filename' : IDL.Text,
    'category' : FormCategory,
  });
  const UpdateProfileRequest = IDL.Record({
    'imageFile' : IDL.Opt(ExternalBlob),
    'fullname' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const UpdateStaffRequest = IDL.Record({
    'branch' : IDL.Opt(Branch),
    'role' : IDL.Opt(Role),
    'department' : IDL.Opt(Department),
    'position' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'archiveStaff' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmPasswordReset' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createAnnouncement' : IDL.Func(
        [CreateAnnouncementInput],
        [AnnouncementPublic],
        [],
      ),
    'createForm' : IDL.Func([CreateFormInput], [Form], []),
    'createNotification' : IDL.Func(
        [CreateNotificationInput],
        [NotificationPublic],
        [],
      ),
    'createPoll' : IDL.Func([CreatePollInput], [Poll], []),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteAuditLog' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteAuditLogs' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteForm' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteStaff' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getActiveStaff' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getAnnouncements' : IDL.Func(
        [],
        [IDL.Vec(AnnouncementWithPoll)],
        ['query'],
      ),
    'getArchivedStaff' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getForms' : IDL.Func([], [IDL.Vec(Form)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(NotificationPublic)], ['query']),
    'getPollResult' : IDL.Func([IDL.Nat], [IDL.Opt(PollResult)], ['query']),
    'getStaffMember' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'getStaffStats' : IDL.Func([], [StaffStats], ['query']),
    'getTrashedAnnouncements' : IDL.Func(
        [],
        [IDL.Vec(AnnouncementPublic)],
        ['query'],
      ),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'hideAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logAction' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'logAnnouncementDownload' : IDL.Func([IDL.Nat], [], []),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
      [],
    ),
  'agmGetSettings' : IDL.Func([IDL.Text], [AgmSettings], ['query']),
  'agmUpdateSettings' : IDL.Func(
      [IDL.Text, IDL.Text, AgmSettings],
      [IDL.Variant({ 'ok' : AgmSettings, 'err' : IDL.Text })],
      [],
    ),
  'agmGetAllShareholders' : IDL.Func([IDL.Text], [IDL.Vec(AgmShareholder)], ['query']),
  'agmGetAllShareholdersSecure' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(AgmShareholder), 'err' : IDL.Text })],
      [],
    ),
  'agmSearchShareholders' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(AgmShareholderStatus), IDL.Nat, IDL.Nat],
      [AgmSearchResult],
      ['query'],
    ),
  'agmSearchShareholdersSecure' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(AgmShareholderStatus), IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : AgmSearchResult, 'err' : IDL.Text })],
      [],
    ),
  'agmGetAllRegistrations' : IDL.Func([IDL.Text], [IDL.Vec(AgmRegistration)], ['query']),
  'agmGetAllCheckIns' : IDL.Func([IDL.Text], [IDL.Vec(AgmCheckIn)], ['query']),
  'agmGetDashboardMetrics' : IDL.Func([IDL.Text, IDL.Nat], [AgmDashboardMetrics], ['query']),
  'agmCreateImportBatch' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [AgmImportBatch],
      [],
    ),
  'agmGetImportBatches' : IDL.Func([IDL.Text], [IDL.Vec(AgmImportBatch)], ['query']),
  'agmBulkCreateShareholders' : IDL.Func(
      [IDL.Text, IDL.Vec(AgmShareholderInput), IDL.Text],
      [AgmBulkCreateResult],
      [],
    ),
  'agmUpdateImportBatchStatus' : IDL.Func(
      [IDL.Text, IDL.Text, AgmImportStatus, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : AgmImportBatch, 'err' : IDL.Text })],
      [],
    ),
  'agmRegisterShareholder' : IDL.Func(
      [IDL.Text, IDL.Text, AgmRegistrationType, IDL.Opt(AgmProxyData), IDL.Text],
      [IDL.Variant({ 'ok' : AgmRegistration, 'err' : IDL.Text })],
      [],
    ),
  'agmGetRegistrationByShareholder' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(AgmRegistration)],
      ['query'],
    ),
  'agmUpdateRegistration' : IDL.Func(
      [IDL.Text, IDL.Text, AgmRegistrationUpdate, IDL.Text],
      [IDL.Variant({ 'ok' : AgmRegistration, 'err' : IDL.Text })],
      [],
    ),
  'agmCancelRegistration' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'agmUndoCheckIn' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'agmUpdateShareholderContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : AgmShareholder, 'err' : IDL.Text })],
      [],
    ),
  'agmCheckInShareholder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, AgmCheckInMethod, IDL.Text],
      [IDL.Variant({ 'ok' : AgmCheckIn, 'err' : IDL.Text })],
      [],
    ),
  'agmGetAuditLog' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Nat],
      [IDL.Vec(AgmAuditEntry)],
      ['query'],
    ),
  'agmLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : AgmLoginResponse, 'err' : IDL.Text })],
      [],
    ),
    'agmValidateSession' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : AgmSession, 'err' : IDL.Text })],
        [],
      ),
    'agmLogout' : IDL.Func([IDL.Text], [], []),
    'agmChangePassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'agmChangePasswordSecure' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'agmResetPasswordWithCode' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'logout' : IDL.Func([], [], []),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'permanentDeleteAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'register' : IDL.Func(
        [RegisterRequest],
        [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
        [],
      ),
    'requestPasswordReset' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'resendVerificationCode' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'restoreAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'restoreStaff' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateAnnouncement' : IDL.Func(
        [UpdateAnnouncementInput],
        [IDL.Opt(AnnouncementPublic)],
        [],
      ),
    'updateForm' : IDL.Func([UpdateFormInput], [IDL.Opt(Form)], []),
    'updateLastSeen' : IDL.Func([], [], []),
    'updateMyProfile' : IDL.Func(
        [UpdateProfileRequest],
        [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
        [],
      ),
    'updateStaff' : IDL.Func(
        [IDL.Principal, UpdateStaffRequest],
        [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
        [],
      ),
    'verifyEmail' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'vote' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };
