name = "include-object-storage"
description = "Include the object storage mixin with `include MixinObjectStorage();`"
query = """
(source_file (obj_dec "actor" (obj_body))) @error
(source_file (class_dec "actor" (obj_body))) @error
(source_file
  (obj_dec "actor"
   (obj_body
    (dec_field (include_dec (identifier) @mixin))))
   (#eq? @mixin "MixinObjectStorage")) @filter
(source_file
  (class_dec "actor"
   (obj_body
    (dec_field (include_dec (identifier) @mixin))))
   (#eq? @mixin "MixinObjectStorage")) @filter
"""
