name = "no-redeclare-immutable-object-storage-refill"
description = "Do NOT redeclare _immutableObjectStorageRefillCashier — it is provided by MixinStorage"
query = """
(source_file
  (obj_dec "actor"
    (obj_body
      (dec_field
        (func_dec
          (_) @error
          (#eq? @error "_immutableObjectStorageRefillCashier"))))))
(source_file
  (class_dec "actor"
    (obj_body
      (dec_field
        (func_dec
          (_) @error
          (#eq? @error "_immutableObjectStorageRefillCashier"))))))
"""
