/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UpdateAnnouncementInput {
    id: bigint;
    title: string;
    imageFile?: ExternalBlob;
    body: string;
    allowDownload: boolean;
    category: AnnouncementCategory;
}
export type Timestamp = bigint;
export interface PollOptionResult {
    votedByMe: boolean;
    optionId: bigint;
    voteCount: bigint;
    optionText: string;
}
export interface AuditLog {
    id: bigint;
    action: string;
    actorName: string;
    target: string;
    timestamp: bigint;
    ipAddress: string;
}
export interface Form {
    id: bigint;
    title: string;
    filename: string;
    category: FormCategory;
    uploadDate: Timestamp;
}
export interface Poll {
    id: bigint;
    question: string;
    announcementId: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface PollResult {
    question: string;
    options: Array<PollOptionResult>;
    pollId: bigint;
}
export interface UpdateProfileRequest {
    imageFile?: ExternalBlob;
    fullname?: string;
    phone?: string;
}
export interface RegisterRequest {
    branch: Branch;
    accessCode?: string;
    email: string;
    fullname: string;
    passwordHash: string;
    phone: string;
    department: Department;
    position: string;
}
export interface CreatePollInput {
    question: string;
    options: Array<string>;
    announcementId: bigint;
}
export interface CreateAnnouncementInput {
    title: string;
    imageFile?: ExternalBlob;
    body: string;
    authorName: string;
    allowDownload: boolean;
    category: AnnouncementCategory;
}
export interface UpdateFormInput {
    id: bigint;
    title: string;
    filename: string;
    category: FormCategory;
}
export interface CreateFormInput {
    title: string;
    filename: string;
    category: FormCategory;
}
export interface NotificationPublic {
    id: bigint;
    title: string;
    userId: string;
    link?: string;
    createdAt: Timestamp;
    isRead: boolean;
    message: string;
}
export interface StaffStats {
    branchesWithStaff: bigint;
    activeCount: bigint;
    archivedCount: bigint;
}
export interface User {
    id: Principal;
    branch: Branch;
    imageFile?: Uint8Array;
    role: Role;
    isArchived: boolean;
    isActive: boolean;
    email: string;
    fullname: string;
    isVerified: boolean;
    phone: string;
    department: Department;
    position: string;
    registrationTime: bigint;
    lastSeen: bigint;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface AnnouncementPublic {
    id: bigint;
    title: string;
    isDeleted: boolean;
    imageFile?: ExternalBlob;
    authorId: string;
    body: string;
    authorName: string;
    allowDownload: boolean;
    datePosted: Timestamp;
    category: AnnouncementCategory;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface AnnouncementWithPoll {
    poll?: PollResult;
    announcement: AnnouncementPublic;
}
export interface CreateNotificationInput {
    title: string;
    userId: UserId;
    link?: string;
    message: string;
}
export type UserId = Principal;
export interface UpdateStaffRequest {
    branch?: Branch;
    role?: Role;
    department?: Department;
    position?: string;
}
export enum AnnouncementCategory {
    HR = "HR",
    IT = "IT",
    General = "General"
}
export enum Branch {
    Bawjiase = "Bawjiase",
    KasoaMain = "KasoaMain",
    Ofaakor = "Ofaakor",
    HeadOffice = "HeadOffice",
    Adeiso = "Adeiso",
    KasoaNewMarket = "KasoaNewMarket"
}
export enum Department {
    HR = "HR",
    IT = "IT",
    Susu = "Susu",
    Compliance = "Compliance",
    Bawjiase = "Bawjiase",
    Recovery = "Recovery",
    EBanking = "EBanking",
    KasoaMain = "KasoaMain",
    Admin = "Admin",
    Credit = "Credit",
    Ofaakor = "Ofaakor",
    Audit = "Audit",
    HeadOffice = "HeadOffice",
    Adeiso = "Adeiso",
    KasoaNewMarket = "KasoaNewMarket",
    Microfinance = "Microfinance",
    BankingOperations = "BankingOperations"
}
export enum FormCategory {
    HR = "HR",
    IT = "IT",
    General = "General",
    Operations = "Operations",
    Finance = "Finance"
}
export enum Role {
    HRAdmin = "HRAdmin",
    GeneralStaff = "GeneralStaff",
    SuperAdmin = "SuperAdmin"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    archiveStaff(userId: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    confirmPasswordReset(token: string, newPasswordHash: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createAnnouncement(input: CreateAnnouncementInput): Promise<AnnouncementPublic>;
    createForm(input: CreateFormInput): Promise<Form>;
    createNotification(input: CreateNotificationInput): Promise<NotificationPublic>;
    createPoll(input: CreatePollInput): Promise<Poll>;
    deleteAnnouncement(id: bigint): Promise<boolean>;
    deleteAuditLog(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteAuditLogs(ids: Array<bigint>): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteForm(id: bigint): Promise<boolean>;
    deleteStaff(userId: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getActiveStaff(): Promise<Array<User>>;
    getAnnouncements(): Promise<Array<AnnouncementWithPoll>>;
    getArchivedStaff(): Promise<Array<User>>;
    getAuditLogs(): Promise<Array<AuditLog>>;
    getCallerUserRole(): Promise<UserRole>;
    getForms(): Promise<Array<Form>>;
    getMyProfile(): Promise<User | null>;
    getNotifications(): Promise<Array<NotificationPublic>>;
    getPollResult(announcementId: bigint): Promise<PollResult | null>;
    getStaffMember(userId: Principal): Promise<User | null>;
    getStaffStats(): Promise<StaffStats>;
    getTrashedAnnouncements(): Promise<Array<AnnouncementPublic>>;
    getUnreadNotificationCount(): Promise<bigint>;
    hideAnnouncement(announcementId: bigint): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    logAction(actorName: string, action: string, target: string, ipAddress: string): Promise<void>;
    logAnnouncementDownload(announcementId: bigint): Promise<void>;
    login(email: string, passwordHash: string): Promise<{
        __kind__: "ok";
        ok: User;
    } | {
        __kind__: "err";
        err: string;
    }>;
    agmGetSettings(): Promise<any>;
    agmUpdateSettings(token: string, settings: any): Promise<any>;
    agmGetAllShareholders(): Promise<any>;
    agmGetAllShareholdersSecure(token: string): Promise<any>;
    agmSearchShareholders(query: string, statusFilter: any, page: bigint, pageSize: bigint): Promise<any>;
    agmSearchShareholdersSecure(token: string, query: string, statusFilter: any, page: bigint, pageSize: bigint): Promise<any>;
    agmGetAllRegistrations(): Promise<any>;
    agmGetAllCheckIns(): Promise<any>;
    agmGetDashboardMetrics(quorumThreshold: bigint): Promise<any>;
    agmCreateImportBatch(filename: string, uploadedBy: string, totalRows: bigint): Promise<any>;
    agmGetImportBatches(): Promise<any>;
    agmBulkCreateShareholders(items: any[], importedBy: string): Promise<any>;
    agmUpdateImportBatchStatus(id: string, status: any, importedRows: bigint, duplicates: bigint): Promise<any>;
    agmRegisterShareholder(shareholderId: string, regType: any, proxyData: any, registeredBy: string): Promise<any>;
    agmGetRegistrationByShareholder(shareholderId: string): Promise<any>;
    agmUpdateRegistration(id: string, updates: any, updatedBy: string): Promise<any>;
    agmCancelRegistration(id: string, cancelledBy: string, reason: string): Promise<any>;
    agmUndoCheckIn(shareholderId: string, undoneBy: string): Promise<any>;
    agmUpdateShareholderContact(id: string, phone: string[] | [], idNumber: string, updatedBy: string): Promise<any>;
    agmCheckInShareholder(shareholderId: string, registrationId: string, method: any, checkedInBy: string): Promise<any>;
    agmGetAuditLog(entityType: string[] | [], entityId: string[] | [], limit: bigint): Promise<any>;
    logout(): Promise<void>;
    markAllNotificationsRead(): Promise<void>;
    markNotificationRead(id: bigint): Promise<boolean>;
    permanentDeleteAnnouncement(id: bigint): Promise<boolean>;
    register(req: RegisterRequest): Promise<{
        __kind__: "ok";
        ok: User;
    } | {
        __kind__: "err";
        err: string;
    }>;
    requestPasswordReset(email: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    resendVerificationCode(email: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    restoreAnnouncement(id: bigint): Promise<boolean>;
    restoreStaff(userId: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateAnnouncement(input: UpdateAnnouncementInput): Promise<AnnouncementPublic | null>;
    updateForm(input: UpdateFormInput): Promise<Form | null>;
    updateLastSeen(): Promise<void>;
    updateMyProfile(req: UpdateProfileRequest): Promise<{
        __kind__: "ok";
        ok: User;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateStaff(userId: Principal, req: UpdateStaffRequest): Promise<{
        __kind__: "ok";
        ok: User;
    } | {
        __kind__: "err";
        err: string;
    }>;
    verifyEmail(email: string, code: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    vote(pollId: bigint, optionId: bigint): Promise<boolean>;
}
import type { AnnouncementCategory as _AnnouncementCategory, AnnouncementPublic as _AnnouncementPublic, AnnouncementWithPoll as _AnnouncementWithPoll, Branch as _Branch, CreateAnnouncementInput as _CreateAnnouncementInput, CreateFormInput as _CreateFormInput, CreateNotificationInput as _CreateNotificationInput, Department as _Department, ExternalBlob as _ExternalBlob, Form as _Form, FormCategory as _FormCategory, NotificationPublic as _NotificationPublic, PollResult as _PollResult, RegisterRequest as _RegisterRequest, Role as _Role, Timestamp as _Timestamp, UpdateAnnouncementInput as _UpdateAnnouncementInput, UpdateFormInput as _UpdateFormInput, UpdateProfileRequest as _UpdateProfileRequest, UpdateStaffRequest as _UpdateStaffRequest, User as _User, UserId as _UserId, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async archiveStaff(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveStaff(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveStaff(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async confirmPasswordReset(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmPasswordReset(arg0, arg1);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmPasswordReset(arg0, arg1);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createAnnouncement(arg0: CreateAnnouncementInput): Promise<AnnouncementPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnnouncement(await to_candid_CreateAnnouncementInput_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AnnouncementPublic_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnnouncement(await to_candid_CreateAnnouncementInput_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AnnouncementPublic_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async createForm(arg0: CreateFormInput): Promise<Form> {
        if (this.processError) {
            try {
                const result = await this.actor.createForm(to_candid_CreateFormInput_n22(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Form_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createForm(to_candid_CreateFormInput_n22(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Form_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async createNotification(arg0: CreateNotificationInput): Promise<NotificationPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(to_candid_CreateNotificationInput_n30(this._uploadFile, this._downloadFile, arg0));
                return from_candid_NotificationPublic_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(to_candid_CreateNotificationInput_n30(this._uploadFile, this._downloadFile, arg0));
            return from_candid_NotificationPublic_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPoll(arg0: CreatePollInput): Promise<Poll> {
        if (this.processError) {
            try {
                const result = await this.actor.createPoll(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPoll(arg0);
            return result;
        }
    }
    async deleteAnnouncement(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnouncement(arg0);
            return result;
        }
    }
    async deleteAuditLog(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAuditLog(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAuditLog(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAuditLogs(arg0: Array<bigint>): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAuditLogs(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAuditLogs(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteForm(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteForm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteForm(arg0);
            return result;
        }
    }
    async deleteStaff(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStaff(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStaff(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveStaff(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveStaff();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveStaff();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnnouncements(): Promise<Array<AnnouncementWithPoll>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnouncements();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnouncements();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArchivedStaff(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArchivedStaff();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArchivedStaff();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditLogs(): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogs();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getForms(): Promise<Array<Form>> {
        if (this.processError) {
            try {
                const result = await this.actor.getForms();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getForms();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<NotificationPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPollResult(arg0: bigint): Promise<PollResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPollResult(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPollResult(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStaffMember(arg0: Principal): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffMember(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffMember(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStaffStats(): Promise<StaffStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffStats();
            return result;
        }
    }
    async getTrashedAnnouncements(): Promise<Array<AnnouncementPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrashedAnnouncements();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrashedAnnouncements();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount();
            return result;
        }
    }
    async hideAnnouncement(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.hideAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hideAnnouncement(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logAction(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logAction(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logAction(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async logAnnouncementDownload(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logAnnouncementDownload(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logAnnouncementDownload(arg0);
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: User;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_variant_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_variant_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async agmGetSettings(): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).agmGetSettings();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).agmGetSettings();
        }
    }
    async agmUpdateSettings(arg0: string, arg1: any): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).agmUpdateSettings(arg0, arg1);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).agmUpdateSettings(arg0, arg1);
        }
    }
    async agmGetAllShareholders(): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).agmGetAllShareholders();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).agmGetAllShareholders();
        }
    }
    async agmGetAllShareholdersSecure(arg0: string): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).agmGetAllShareholdersSecure(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).agmGetAllShareholdersSecure(arg0);
        }
    }
    async agmSearchShareholders(arg0: string, arg1: any, arg2: bigint, arg3: bigint): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).agmSearchShareholders(arg0, arg1, arg2, arg3);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).agmSearchShareholders(arg0, arg1, arg2, arg3);
        }
    }
    async agmSearchShareholdersSecure(arg0: string, arg1: string, arg2: any, arg3: bigint, arg4: bigint): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).agmSearchShareholdersSecure(arg0, arg1, arg2, arg3, arg4);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).agmSearchShareholdersSecure(arg0, arg1, arg2, arg3, arg4);
        }
    }
    async agmGetAllRegistrations(): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).agmGetAllRegistrations();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).agmGetAllRegistrations();
        }
    }
    async agmGetAllCheckIns(): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).agmGetAllCheckIns();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).agmGetAllCheckIns();
        }
    }
    async agmGetDashboardMetrics(arg0: bigint): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).agmGetDashboardMetrics(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).agmGetDashboardMetrics(arg0);
        }
    }
    async agmCreateImportBatch(arg0: string, arg1: string, arg2: bigint): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).agmCreateImportBatch(arg0, arg1, arg2);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).agmCreateImportBatch(arg0, arg1, arg2);
        }
    }
    async agmGetImportBatches(): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).agmGetImportBatches();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).agmGetImportBatches();
        }
    }
    async agmBulkCreateShareholders(arg0: any[], arg1: string): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).agmBulkCreateShareholders(arg0, arg1);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).agmBulkCreateShareholders(arg0, arg1);
        }
    }
    async agmUpdateImportBatchStatus(arg0: string, arg1: any, arg2: bigint, arg3: bigint): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).agmUpdateImportBatchStatus(arg0, arg1, arg2, arg3);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).agmUpdateImportBatchStatus(arg0, arg1, arg2, arg3);
        }
    }
    async agmRegisterShareholder(arg0: string, arg1: any, arg2: any, arg3: string): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).agmRegisterShareholder(arg0, arg1, arg2, arg3);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).agmRegisterShareholder(arg0, arg1, arg2, arg3);
        }
    }
    async agmGetRegistrationByShareholder(arg0: string): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).agmGetRegistrationByShareholder(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).agmGetRegistrationByShareholder(arg0);
        }
    }
    async agmUpdateRegistration(arg0: string, arg1: any, arg2: string): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).agmUpdateRegistration(arg0, arg1, arg2);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).agmUpdateRegistration(arg0, arg1, arg2);
        }
    }
    async agmCancelRegistration(arg0: string, arg1: string, arg2: string): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).agmCancelRegistration(arg0, arg1, arg2);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).agmCancelRegistration(arg0, arg1, arg2);
        }
    }
    async agmUndoCheckIn(arg0: string, arg1: string): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).agmUndoCheckIn(arg0, arg1);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).agmUndoCheckIn(arg0, arg1);
        }
    }
    async agmUpdateShareholderContact(arg0: string, arg1: string[] | [], arg2: string, arg3: string): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).agmUpdateShareholderContact(arg0, arg1, arg2, arg3);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).agmUpdateShareholderContact(arg0, arg1, arg2, arg3);
        }
    }
    async agmCheckInShareholder(arg0: string, arg1: string, arg2: any, arg3: string): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).agmCheckInShareholder(arg0, arg1, arg2, arg3);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).agmCheckInShareholder(arg0, arg1, arg2, arg3);
        }
    }
    async agmGetAuditLog(arg0: string[] | [], arg1: string[] | [], arg2: bigint): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).agmGetAuditLog(arg0, arg1, arg2);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).agmGetAuditLog(arg0, arg1, arg2);
        }
    }
    async logout(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout();
            return result;
        }
    }
    async markAllNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markNotificationRead(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async permanentDeleteAnnouncement(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.permanentDeleteAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.permanentDeleteAnnouncement(arg0);
            return result;
        }
    }
    async register(arg0: RegisterRequest): Promise<{
        __kind__: "ok";
        ok: User;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.register(to_candid_RegisterRequest_n56(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(to_candid_RegisterRequest_n56(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestPasswordReset(arg0: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.requestPasswordReset(arg0);
                return from_candid_variant_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestPasswordReset(arg0);
            return from_candid_variant_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async resendVerificationCode(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.resendVerificationCode(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resendVerificationCode(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async restoreAnnouncement(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreAnnouncement(arg0);
            return result;
        }
    }
    async restoreStaff(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreStaff(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreStaff(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAnnouncement(arg0: UpdateAnnouncementInput): Promise<AnnouncementPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnnouncement(await to_candid_UpdateAnnouncementInput_n63(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnnouncement(await to_candid_UpdateAnnouncementInput_n63(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateForm(arg0: UpdateFormInput): Promise<Form | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateForm(to_candid_UpdateFormInput_n66(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateForm(to_candid_UpdateFormInput_n66(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLastSeen(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLastSeen();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLastSeen();
            return result;
        }
    }
    async updateMyProfile(arg0: UpdateProfileRequest): Promise<{
        __kind__: "ok";
        ok: User;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(await to_candid_UpdateProfileRequest_n69(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(await to_candid_UpdateProfileRequest_n69(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateStaff(arg0: Principal, arg1: UpdateStaffRequest): Promise<{
        __kind__: "ok";
        ok: User;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaff(arg0, to_candid_UpdateStaffRequest_n71(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaff(arg0, to_candid_UpdateStaffRequest_n71(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyEmail(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyEmail(arg0, arg1);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyEmail(arg0, arg1);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async vote(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.vote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.vote(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AnnouncementCategory_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnnouncementCategory): AnnouncementCategory {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_AnnouncementPublic_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnnouncementPublic): Promise<AnnouncementPublic> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_AnnouncementWithPoll_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnnouncementWithPoll): Promise<AnnouncementWithPoll> {
    return await from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Branch_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Branch): Branch {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Department_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Department): Department {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FormCategory_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FormCategory): FormCategory {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Form_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Form): Form {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationPublic_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationPublic): NotificationPublic {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_User_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PollResult]): PollResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AnnouncementPublic]): Promise<AnnouncementPublic | null> {
    return value.length === 0 ? null : await from_candid_AnnouncementPublic_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Form]): Form | null {
    return value.length === 0 ? null : from_candid_Form_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    isDeleted: boolean;
    imageFile: [] | [_ExternalBlob];
    authorId: string;
    body: string;
    authorName: string;
    allowDownload: boolean;
    datePosted: _Timestamp;
    category: _AnnouncementCategory;
}): Promise<{
    id: bigint;
    title: string;
    isDeleted: boolean;
    imageFile?: ExternalBlob;
    authorId: string;
    body: string;
    authorName: string;
    allowDownload: boolean;
    datePosted: Timestamp;
    category: AnnouncementCategory;
}> {
    return {
        id: value.id,
        title: value.title,
        isDeleted: value.isDeleted,
        imageFile: record_opt_to_undefined(await from_candid_opt_n18(_uploadFile, _downloadFile, value.imageFile)),
        authorId: value.authorId,
        body: value.body,
        authorName: value.authorName,
        allowDownload: value.allowDownload,
        datePosted: value.datePosted,
        category: from_candid_AnnouncementCategory_n20(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    filename: string;
    category: _FormCategory;
    uploadDate: _Timestamp;
}): {
    id: bigint;
    title: string;
    filename: string;
    category: FormCategory;
    uploadDate: Timestamp;
} {
    return {
        id: value.id,
        title: value.title,
        filename: value.filename,
        category: from_candid_FormCategory_n28(_uploadFile, _downloadFile, value.category),
        uploadDate: value.uploadDate
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    userId: string;
    link: [] | [string];
    createdAt: _Timestamp;
    isRead: boolean;
    message: string;
}): {
    id: bigint;
    title: string;
    userId: string;
    link?: string;
    createdAt: Timestamp;
    isRead: boolean;
    message: string;
} {
    return {
        id: value.id,
        title: value.title,
        userId: value.userId,
        link: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.link)),
        createdAt: value.createdAt,
        isRead: value.isRead,
        message: value.message
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    branch: _Branch;
    imageFile: [] | [Uint8Array];
    role: _Role;
    isArchived: boolean;
    isActive: boolean;
    email: string;
    fullname: string;
    isVerified: boolean;
    phone: string;
    department: _Department;
    position: string;
    registrationTime: bigint;
    lastSeen: bigint;
}): {
    id: Principal;
    branch: Branch;
    imageFile?: Uint8Array;
    role: Role;
    isArchived: boolean;
    isActive: boolean;
    email: string;
    fullname: string;
    isVerified: boolean;
    phone: string;
    department: Department;
    position: string;
    registrationTime: bigint;
    lastSeen: bigint;
} {
    return {
        id: value.id,
        branch: from_candid_Branch_n38(_uploadFile, _downloadFile, value.branch),
        imageFile: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.imageFile)),
        role: from_candid_Role_n41(_uploadFile, _downloadFile, value.role),
        isArchived: value.isArchived,
        isActive: value.isActive,
        email: value.email,
        fullname: value.fullname,
        isVerified: value.isVerified,
        phone: value.phone,
        department: from_candid_Department_n43(_uploadFile, _downloadFile, value.department),
        position: value.position,
        registrationTime: value.registrationTime,
        lastSeen: value.lastSeen
    };
}
async function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    poll: [] | [_PollResult];
    announcement: _AnnouncementPublic;
}): Promise<{
    poll?: PollResult;
    announcement: AnnouncementPublic;
}> {
    return {
        poll: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.poll)),
        announcement: await from_candid_AnnouncementPublic_n16(_uploadFile, _downloadFile, value.announcement)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    HR: null;
} | {
    IT: null;
} | {
    General: null;
}): AnnouncementCategory {
    return "HR" in value ? AnnouncementCategory.HR : "IT" in value ? AnnouncementCategory.IT : "General" in value ? AnnouncementCategory.General : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    HR: null;
} | {
    IT: null;
} | {
    General: null;
} | {
    Operations: null;
} | {
    Finance: null;
}): FormCategory {
    return "HR" in value ? FormCategory.HR : "IT" in value ? FormCategory.IT : "General" in value ? FormCategory.General : "Operations" in value ? FormCategory.Operations : "Finance" in value ? FormCategory.Finance : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Bawjiase: null;
} | {
    KasoaMain: null;
} | {
    Ofaakor: null;
} | {
    HeadOffice: null;
} | {
    Adeiso: null;
} | {
    KasoaNewMarket: null;
}): Branch {
    return "Bawjiase" in value ? Branch.Bawjiase : "KasoaMain" in value ? Branch.KasoaMain : "Ofaakor" in value ? Branch.Ofaakor : "HeadOffice" in value ? Branch.HeadOffice : "Adeiso" in value ? Branch.Adeiso : "KasoaNewMarket" in value ? Branch.KasoaNewMarket : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    HRAdmin: null;
} | {
    GeneralStaff: null;
} | {
    SuperAdmin: null;
}): Role {
    return "HRAdmin" in value ? Role.HRAdmin : "GeneralStaff" in value ? Role.GeneralStaff : "SuperAdmin" in value ? Role.SuperAdmin : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    HR: null;
} | {
    IT: null;
} | {
    Susu: null;
} | {
    Compliance: null;
} | {
    Bawjiase: null;
} | {
    Recovery: null;
} | {
    EBanking: null;
} | {
    KasoaMain: null;
} | {
    Admin: null;
} | {
    Credit: null;
} | {
    Ofaakor: null;
} | {
    Audit: null;
} | {
    HeadOffice: null;
} | {
    Adeiso: null;
} | {
    KasoaNewMarket: null;
} | {
    Microfinance: null;
} | {
    BankingOperations: null;
}): Department {
    return "HR" in value ? Department.HR : "IT" in value ? Department.IT : "Susu" in value ? Department.Susu : "Compliance" in value ? Department.Compliance : "Bawjiase" in value ? Department.Bawjiase : "Recovery" in value ? Department.Recovery : "EBanking" in value ? Department.EBanking : "KasoaMain" in value ? Department.KasoaMain : "Admin" in value ? Department.Admin : "Credit" in value ? Department.Credit : "Ofaakor" in value ? Department.Ofaakor : "Audit" in value ? Department.Audit : "HeadOffice" in value ? Department.HeadOffice : "Adeiso" in value ? Department.Adeiso : "KasoaNewMarket" in value ? Department.KasoaNewMarket : "Microfinance" in value ? Department.Microfinance : "BankingOperations" in value ? Department.BankingOperations : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _User;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_User_n36(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n36(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnnouncementWithPoll>): Promise<Array<AnnouncementWithPoll>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AnnouncementWithPoll_n46(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Form>): Array<Form> {
    return value.map((x)=>from_candid_Form_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NotificationPublic>): Array<NotificationPublic> {
    return value.map((x)=>from_candid_NotificationPublic_n32(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnnouncementPublic>): Promise<Array<AnnouncementPublic>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AnnouncementPublic_n16(_uploadFile, _downloadFile, x)));
}
function to_candid_AnnouncementCategory_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnnouncementCategory): _AnnouncementCategory {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Branch_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Branch): _Branch {
    return to_candid_variant_n59(_uploadFile, _downloadFile, value);
}
async function to_candid_CreateAnnouncementInput_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateAnnouncementInput): Promise<_CreateAnnouncementInput> {
    return await to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_CreateFormInput_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateFormInput): _CreateFormInput {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_CreateNotificationInput_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateNotificationInput): _CreateNotificationInput {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_Department_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Department): _Department {
    return to_candid_variant_n61(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FormCategory_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FormCategory): _FormCategory {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_RegisterRequest_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterRequest): _RegisterRequest {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n74(_uploadFile, _downloadFile, value);
}
async function to_candid_UpdateAnnouncementInput_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateAnnouncementInput): Promise<_UpdateAnnouncementInput> {
    return await to_candid_record_n64(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateFormInput_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateFormInput): _UpdateFormInput {
    return to_candid_record_n67(_uploadFile, _downloadFile, value);
}
async function to_candid_UpdateProfileRequest_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProfileRequest): Promise<_UpdateProfileRequest> {
    return await to_candid_record_n70(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateStaffRequest_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateStaffRequest): _UpdateStaffRequest {
    return to_candid_record_n72(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    imageFile?: ExternalBlob;
    body: string;
    authorName: string;
    allowDownload: boolean;
    category: AnnouncementCategory;
}): Promise<{
    title: string;
    imageFile: [] | [_ExternalBlob];
    body: string;
    authorName: string;
    allowDownload: boolean;
    category: _AnnouncementCategory;
}> {
    return {
        title: value.title,
        imageFile: value.imageFile ? candid_some(await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.imageFile)) : candid_none(),
        body: value.body,
        authorName: value.authorName,
        allowDownload: value.allowDownload,
        category: to_candid_AnnouncementCategory_n14(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    filename: string;
    category: FormCategory;
}): {
    title: string;
    filename: string;
    category: _FormCategory;
} {
    return {
        title: value.title,
        filename: value.filename,
        category: to_candid_FormCategory_n24(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    userId: UserId;
    link?: string;
    message: string;
}): {
    title: string;
    userId: _UserId;
    link: [] | [string];
    message: string;
} {
    return {
        title: value.title,
        userId: value.userId,
        link: value.link ? candid_some(value.link) : candid_none(),
        message: value.message
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    branch: Branch;
    accessCode?: string;
    email: string;
    fullname: string;
    passwordHash: string;
    phone: string;
    department: Department;
    position: string;
}): {
    branch: _Branch;
    accessCode: [] | [string];
    email: string;
    fullname: string;
    passwordHash: string;
    phone: string;
    department: _Department;
    position: string;
} {
    return {
        branch: to_candid_Branch_n58(_uploadFile, _downloadFile, value.branch),
        accessCode: value.accessCode ? candid_some(value.accessCode) : candid_none(),
        email: value.email,
        fullname: value.fullname,
        passwordHash: value.passwordHash,
        phone: value.phone,
        department: to_candid_Department_n60(_uploadFile, _downloadFile, value.department),
        position: value.position
    };
}
async function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    imageFile?: ExternalBlob;
    body: string;
    allowDownload: boolean;
    category: AnnouncementCategory;
}): Promise<{
    id: bigint;
    title: string;
    imageFile: [] | [_ExternalBlob];
    body: string;
    allowDownload: boolean;
    category: _AnnouncementCategory;
}> {
    return {
        id: value.id,
        title: value.title,
        imageFile: value.imageFile ? candid_some(await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.imageFile)) : candid_none(),
        body: value.body,
        allowDownload: value.allowDownload,
        category: to_candid_AnnouncementCategory_n14(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    filename: string;
    category: FormCategory;
}): {
    id: bigint;
    title: string;
    filename: string;
    category: _FormCategory;
} {
    return {
        id: value.id,
        title: value.title,
        filename: value.filename,
        category: to_candid_FormCategory_n24(_uploadFile, _downloadFile, value.category)
    };
}
async function to_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    imageFile?: ExternalBlob;
    fullname?: string;
    phone?: string;
}): Promise<{
    imageFile: [] | [_ExternalBlob];
    fullname: [] | [string];
    phone: [] | [string];
}> {
    return {
        imageFile: value.imageFile ? candid_some(await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.imageFile)) : candid_none(),
        fullname: value.fullname ? candid_some(value.fullname) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    branch?: Branch;
    role?: Role;
    department?: Department;
    position?: string;
}): {
    branch: [] | [_Branch];
    role: [] | [_Role];
    department: [] | [_Department];
    position: [] | [string];
} {
    return {
        branch: value.branch ? candid_some(to_candid_Branch_n58(_uploadFile, _downloadFile, value.branch)) : candid_none(),
        role: value.role ? candid_some(to_candid_Role_n73(_uploadFile, _downloadFile, value.role)) : candid_none(),
        department: value.department ? candid_some(to_candid_Department_n60(_uploadFile, _downloadFile, value.department)) : candid_none(),
        position: value.position ? candid_some(value.position) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnnouncementCategory): {
    HR: null;
} | {
    IT: null;
} | {
    General: null;
} {
    return value == AnnouncementCategory.HR ? {
        HR: null
    } : value == AnnouncementCategory.IT ? {
        IT: null
    } : value == AnnouncementCategory.General ? {
        General: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FormCategory): {
    HR: null;
} | {
    IT: null;
} | {
    General: null;
} | {
    Operations: null;
} | {
    Finance: null;
} {
    return value == FormCategory.HR ? {
        HR: null
    } : value == FormCategory.IT ? {
        IT: null
    } : value == FormCategory.General ? {
        General: null
    } : value == FormCategory.Operations ? {
        Operations: null
    } : value == FormCategory.Finance ? {
        Finance: null
    } : value;
}
function to_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Branch): {
    Bawjiase: null;
} | {
    KasoaMain: null;
} | {
    Ofaakor: null;
} | {
    HeadOffice: null;
} | {
    Adeiso: null;
} | {
    KasoaNewMarket: null;
} {
    return value == Branch.Bawjiase ? {
        Bawjiase: null
    } : value == Branch.KasoaMain ? {
        KasoaMain: null
    } : value == Branch.Ofaakor ? {
        Ofaakor: null
    } : value == Branch.HeadOffice ? {
        HeadOffice: null
    } : value == Branch.Adeiso ? {
        Adeiso: null
    } : value == Branch.KasoaNewMarket ? {
        KasoaNewMarket: null
    } : value;
}
function to_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Department): {
    HR: null;
} | {
    IT: null;
} | {
    Susu: null;
} | {
    Compliance: null;
} | {
    Bawjiase: null;
} | {
    Recovery: null;
} | {
    EBanking: null;
} | {
    KasoaMain: null;
} | {
    Admin: null;
} | {
    Credit: null;
} | {
    Ofaakor: null;
} | {
    Audit: null;
} | {
    HeadOffice: null;
} | {
    Adeiso: null;
} | {
    KasoaNewMarket: null;
} | {
    Microfinance: null;
} | {
    BankingOperations: null;
} {
    return value == Department.HR ? {
        HR: null
    } : value == Department.IT ? {
        IT: null
    } : value == Department.Susu ? {
        Susu: null
    } : value == Department.Compliance ? {
        Compliance: null
    } : value == Department.Bawjiase ? {
        Bawjiase: null
    } : value == Department.Recovery ? {
        Recovery: null
    } : value == Department.EBanking ? {
        EBanking: null
    } : value == Department.KasoaMain ? {
        KasoaMain: null
    } : value == Department.Admin ? {
        Admin: null
    } : value == Department.Credit ? {
        Credit: null
    } : value == Department.Ofaakor ? {
        Ofaakor: null
    } : value == Department.Audit ? {
        Audit: null
    } : value == Department.HeadOffice ? {
        HeadOffice: null
    } : value == Department.Adeiso ? {
        Adeiso: null
    } : value == Department.KasoaNewMarket ? {
        KasoaNewMarket: null
    } : value == Department.Microfinance ? {
        Microfinance: null
    } : value == Department.BankingOperations ? {
        BankingOperations: null
    } : value;
}
function to_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    HRAdmin: null;
} | {
    GeneralStaff: null;
} | {
    SuperAdmin: null;
} {
    return value == Role.HRAdmin ? {
        HRAdmin: null
    } : value == Role.GeneralStaff ? {
        GeneralStaff: null
    } : value == Role.SuperAdmin ? {
        SuperAdmin: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
